baseurl = "/"
RelativeURLs=true
CanonifyURLs=true
languageCode = "en-us"
title = "Chun-Jie Liu | 柳纯洁"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true  # .WordCount works correctly for chinese
enableEmoji = true
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
MetaDataFormat = "yaml" # format of a new post
enableGitInfo = false

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "English"
    url = "/en/"
    weight = 1

[[menu.en]]
    name = "Home"
    url = '/'
    weight = 1

[[menu.en]]
    name = "About"
    url = '/en/about/'
    weight = 2

[[menu.en]]
    name = "Blog"
    url = '/en/post'
    weight = 3

[[menu.en]]
    name = "Project"
    url = '/en/project'
    weight = 4

# [[menu.en]]
#     name = "CV"
#     url = "/en/cv-en/Shixiang"
#     weight = 5

[[menu.main]]
    name = "中文"
    url = '/cn/'
    weight = 2

[[menu.cn]]
    name = "首页"
    url = '/'
    weight = 1

[[menu.cn]]
    name = "关于"
    url = '/cn/about/'
    weight = 2

[[menu.cn]]
    name = "博客"
    url = '/cn/post/'
    weight = 3

# [[menu.cn]]
#     name = "简历"
#     url = "/cn/cv-cn/Shixiang"
#     weight = 4


[params]
    description = "Window to Chun-Jie Liu"
    disqusURL = "https://chunjie-sam-liu.life"
    customJS = ["js/fix-toc.js", "js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js", "js/external-link.js", "js/alt-title.js", "js/header-link.js"]
    githubContentURL = "https://github.com/chunjie-sam-liu/chunjie-sam-liu.life/edit/master/content/"

    highlightjsVersion = "9.12.0"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsTheme = "github"
    dateFormat = "2006-01-02"

[params.footer]
    home = "Powered by [Hugo](https://gohugo.io) and [Blogdown](https://bookdown.org/yihui/blogdown/) &copy; [Chun-Jie Liu](/) 2019 - Present"
    en = "[<i class='far fa-envelope fa-1x'></i>](mailto:chunjie.sam.liu@gmail.com) &middot; [<i class='fab fa-twitter fa-1x'></i>](https://twitter.com/chunjie_sam_liu) &middot; [<i class='fab fa-github fa-1x'></i>](https://github.com/chunjie-sam-liu) &middot; [<i class='ai ai-google-scholar ai-1x'></i>](https://scholar.google.com/citations?user=IBIJfSwAAAAJ&hl=en) &middot; [<i class='ai ai-orcid ai-1x'></i>](https://orcid.org/0000-0002-3008-3375) &middot; [<i class='ai ai-researchgate ai-1x'></i>](https://www.researchgate.net/profile/Chun_Jie_Liu) <br> Powered by [Hugo](https://gohugo.io) and [Blogdown](https://bookdown.org/yihui/blogdown/) &copy; [Chun-Jie Liu](/) 2019 - Present"
    cn = "[<i class='far fa-envelope fa-1x'></i>](mailto:chunjie.sam.liu@gmail.com) &middot; [<i class='fab fa-twitter fa-1x'></i>](https://twitter.com/chunjie_sam_liu) &middot; [<i class='fab fa-github fa-1x'></i>](https://github.com/chunjie-sam-liu) &middot; [<i class='ai ai-google-scholar ai-1x'></i>](https://scholar.google.com/citations?user=IBIJfSwAAAAJ&hl=en) &middot; [<i class='ai ai-orcid ai-1x'></i>](https://orcid.org/0000-0002-3008-3375) &middot; [<i class='ai ai-researchgate ai-1x'></i>](https://www.researchgate.net/profile/Chun_Jie_Liu) <br> Powered by [Hugo](https://gohugo.io) and [Blogdown](https://bookdown.org/yihui/blogdown/) &copy; [Chun-Jie Liu](/) 2019 - Present"

[params.author]
    en = "Chun-Jie Liu"
    cn = "柳纯洁"

[params.logo.en]
    img = "https://www.gravatar.com/avatar/62cc939fa7f1f2537b4847c3eb69401f"
    url = "/"
    alt = "Chun-Jie Liu"
    tag = ""

[params.lang.edit]
    cn = "编辑"
[params.lang.license]
    cn = "版权"
[params.lang.subscribe]
    cn = "订阅"